project_id = "ekzaaptxfwixgmbrooqr"

# Core AI & Photo Functions
[functions.ai-style-analysis]
verify_jwt = false

[functions.analyze-photos]
verify_jwt = false

# eBay Core Integration
[functions.ebay-api-client]
verify_jwt = false

[functions.ebay-category-suggestions]
verify_jwt = false

[functions.ebay-category-sync]
verify_jwt = false

[functions.ebay-inventory-operations]
verify_jwt = false

[functions.ebay-inventory-sync]
verify_jwt = false

[functions.ebay-oauth]
verify_jwt = false

[functions.ebay-policy-manager]
verify_jwt = false

[functions.ebay-shipping-services-fetcher]
verify_jwt = false

[functions.pricing-research]
verify_jwt = false

# Subscription Management
[functions.subscription-management]
verify_jwt = false

[functions.addon-management]
verify_jwt = false