project_id = "ekzaaptxfwixgmbrooqr"

[functions.ai-style-analysis]
verify_jwt = true

[functions.ebay-oauth-modern]
verify_jwt = true

[functions.ebay-batch-publisher]
verify_jwt = true

[functions.ebay-category-suggestions]
verify_jwt = true

[functions.ebay-category-sync]
verify_jwt = true

[functions.ebay-integration]
verify_jwt = true

[functions.ebay-inventory]
verify_jwt = true

[functions.ebay-inventory-item]
verify_jwt = true

[functions.ebay-inventory-sync]
verify_jwt = true

[functions.ebay-item-aspects]
verify_jwt = true

[functions.ebay-listing-publisher]
verify_jwt = true

[functions.ebay-offer-manager]
verify_jwt = true

[functions.ebay-oauth]
verify_jwt = false

[functions.ebay-sync]
verify_jwt = true

[functions.subscription-management]
verify_jwt = true

[functions.posting-queue]
verify_jwt = false